import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
test('admin plain text preserves newlines and renders HTML-looking text literally',async t=>{
 const html=await readFile(new URL('../public/admin.html',import.meta.url),'utf8');
 const script=await readFile(new URL('../public/admin.js',import.meta.url),'utf8');
 const dom=new JSDOM(html,{url:'http://localhost/admin',runScripts:'outside-only'});
 t.after(()=>dom.window.close());
 const w=dom.window;
 w.fetch=async path=>({ok:true,json:async()=>path==='/api/me'?{user:{role:'admin',name:'Test'}}:{users:[],exams:[]}});
 w.alert=()=>{};
 w.eval(script);
 await new Promise(r=>setTimeout(r,50));
 const field=w.document.querySelector('#q-prompt');
 assert.equal(w.document.querySelector('.toolbar-btn'),null);
 field.value='First line\n2 < 3 & <b>literal text</b>';
 field.dispatchEvent(new w.Event('input'));
 const preview=w.document.querySelector('.plain-question-preview');
 assert.equal(preview.textContent,field.value);
 assert.equal(preview.querySelector('b'),null);
 const option=w.document.querySelector('.opt-text');
 option.value='<img src=x onerror=alert(1)>';
 option.dispatchEvent(new w.Event('input'));
 assert.ok(w.document.querySelector('#preview-render').textContent.includes(option.value));
 assert.equal(w.document.querySelector('#preview-render img'),null);
 w.document.querySelector('#q-id').value='q1';
 w.document.querySelector('#btn-save-question').click();
 assert.ok(w.document.querySelector('#questions-summary-list').textContent.includes('2 < 3 & <b>literal text</b>'));
});
