export async function migrate(database) {
  await database.transaction(async query => {
    for (const sql of [
      `CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, login_id TEXT NOT NULL UNIQUE, name TEXT NOT NULL,password_hash TEXT NOT NULL, phone TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('student','teacher','admin')),active INTEGER NOT NULL DEFAULT 1, created_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS auth_challenges (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),provider_session TEXT NOT NULL,expires_at BIGINT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0)`,
      `CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),created_at BIGINT NOT NULL,expires_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS login_history (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),logged_in_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS auth_limits (bucket TEXT PRIMARY KEY,count INTEGER NOT NULL,expires_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS exams (id TEXT PRIMARY KEY,title TEXT NOT NULL,definition TEXT NOT NULL,created_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS exam_assignments (exam_id TEXT NOT NULL REFERENCES exams(id),user_id TEXT NOT NULL REFERENCES users(id),PRIMARY KEY(exam_id,user_id))`,
      `CREATE TABLE IF NOT EXISTS attempts (id TEXT PRIMARY KEY,exam_id TEXT NOT NULL REFERENCES exams(id),user_id TEXT NOT NULL REFERENCES users(id),exam_json TEXT NOT NULL,answers_json TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('active','submitted')),started_at BIGINT NOT NULL,deadline BIGINT NOT NULL,version INTEGER NOT NULL,submitted_at BIGINT,result_json TEXT,UNIQUE(exam_id,user_id))`,
      `CREATE TABLE IF NOT EXISTS answer_mutations (attempt_id TEXT NOT NULL REFERENCES attempts(id),id TEXT NOT NULL,PRIMARY KEY(attempt_id,id))`,
      `CREATE TABLE IF NOT EXISTS activity_flags (id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL REFERENCES attempts(id),user_id TEXT NOT NULL REFERENCES users(id),type TEXT NOT NULL,created_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS attempt_controls (attempt_id TEXT PRIMARY KEY REFERENCES attempts(id),paused_at BIGINT,offset_ms BIGINT NOT NULL DEFAULT 0,locked INTEGER NOT NULL DEFAULT 0)`,
      `CREATE TABLE IF NOT EXISTS teacher_actions (id TEXT PRIMARY KEY,attempt_id TEXT NOT NULL REFERENCES attempts(id),actor_id TEXT NOT NULL REFERENCES users(id),action TEXT NOT NULL,created_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS practice_sets (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),title TEXT NOT NULL,filters_json TEXT NOT NULL,question_ids_json TEXT NOT NULL,total_questions INTEGER NOT NULL,completed_questions INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL DEFAULT 'in_progress',created_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS practice_answers (set_id TEXT NOT NULL REFERENCES practice_sets(id) ON DELETE CASCADE,question_id TEXT NOT NULL,answer_json TEXT NOT NULL,answered_at BIGINT NOT NULL,PRIMARY KEY(set_id,question_id))`,
      `CREATE TABLE IF NOT EXISTS practice_outcomes (set_id TEXT NOT NULL REFERENCES practice_sets(id) ON DELETE CASCADE,question_id TEXT NOT NULL,exam_id TEXT NOT NULL,outcome TEXT NOT NULL,marks REAL NOT NULL,updated_at BIGINT NOT NULL,PRIMARY KEY(set_id,question_id))`,
      `CREATE TABLE IF NOT EXISTS practice_bookmarks (user_id TEXT NOT NULL REFERENCES users(id),question_id TEXT NOT NULL,exam_id TEXT NOT NULL,created_at BIGINT NOT NULL,PRIMARY KEY(user_id,question_id,exam_id))`,
      `CREATE TABLE IF NOT EXISTS student_preferences (user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,preferences_json TEXT NOT NULL,updated_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS gk_card_progress (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,card_id TEXT NOT NULL,box INTEGER NOT NULL DEFAULT 0,seen_count INTEGER NOT NULL DEFAULT 0,last_reviewed_at BIGINT NOT NULL,PRIMARY KEY(user_id,card_id))`,
      `CREATE TABLE IF NOT EXISTS student_sketches (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,title TEXT NOT NULL,prompt TEXT NOT NULL,image_data_url TEXT NOT NULL,created_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS guide_quiz_attempts (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,guide_id TEXT NOT NULL,correct INTEGER NOT NULL,total INTEGER NOT NULL,submitted_at BIGINT NOT NULL)`,
      `CREATE TABLE IF NOT EXISTS student_revision_reviews (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,exam_id TEXT NOT NULL,question_id TEXT NOT NULL,reviewed_at BIGINT NOT NULL,PRIMARY KEY(user_id,exam_id,question_id))`,
      'CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id)',
      'CREATE INDEX IF NOT EXISTS challenges_user ON auth_challenges(user_id)',
      'CREATE INDEX IF NOT EXISTS attempts_deadline ON attempts(status,deadline)',
      'CREATE INDEX IF NOT EXISTS flags_attempt ON activity_flags(attempt_id,type,created_at)',
      'CREATE INDEX IF NOT EXISTS practice_sets_user ON practice_sets(user_id)',
      'CREATE INDEX IF NOT EXISTS student_sketches_user ON student_sketches(user_id,created_at)',
      'CREATE INDEX IF NOT EXISTS guide_quiz_user ON guide_quiz_attempts(user_id,submitted_at)',
      "UPDATE system_metadata SET value = '6' WHERE key = 'schema_version'",
    ]) await query(sql);
  });
}
